version: '3.8'

services:
  # Backend API
  backend:
    build: ./backend
    container_name: notes-backend
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=production
      - PORT=5002
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - OPENSEARCH_URL=${OPENSEARCH_URL}
      - CORS_ORIGIN=${CORS_ORIGIN}
    depends_on:
      - opensearch
    restart: unless-stopped
    networks:
      - app-network

  # OpenSearch
  opensearch:
    image: opensearchproject/opensearch:2.14.0
    container_name: opensearch-node1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_SECURITY_PLUGIN=true
    ports:
      - "9200:9200"
      - "9600:9600"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - app-network
    restart: unless-stopped

  # Frontend (if deploying full stack)
  frontend:
    build: ./notes-frontend
    container_name: notes-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=${API_URL}
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  opensearch-data:

networks:
  app-network:
    driver: bridge
