# Railway deployment configuration
# This file tells Railway how to build and deploy your application

# Build configuration
build:
  # Use Nixpacks for automatic dependency detection
  builder: NIXPACKS
  
  # Build commands (if needed)
  # buildCommand: npm run build
  
  # Start command
  startCommand: npm start

# Deployment configuration
deploy:
  # Number of replicas to run
  numReplicas: 1
  
  # Restart policy
  restartPolicyType: ON_FAILURE
  restartPolicyMaxRetries: 10
  
  # Health check
  healthcheckPath: /api
  healthcheckTimeout: 300
  
  # Environment variables (will be set in Railway dashboard)
  # MONGO_URI: mongodb://your-mongo-connection-string
  # JWT_SECRET: your-jwt-secret
  # OPENSEARCH_URL: your-opensearch-url
  # CORS_ORIGIN: your-frontend-url
